name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[maven-release-plugin] prepare release') }}
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
